version: '3.8'

services:
  db:
    image: postgres:15
    container_name: reviewflow_db
    restart: always
    environment:
      # In prod, move this to an env file and use a manager like 1password
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reviewflow
    ports:
      - "4321:4321"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: reviewflow_api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db/reviewflow
    ports:
      - "7000:7000"
    volumes:
      - review_flow:/app

volumes:
  postgres_data:
